(PDB-5190) Eliminate all reflection warnings
puppetlabs/clj-i18n pull request #49
Opened 2021-07-22 21:53 UTC by rbrw

[See the individual commits for additional comments.]

(Some very simplistic) PuppetDB query performance profiling revealed that reflection in some of the calls in i18n (e.g. underneath bundle-for-namespace, likely via trs/tru) were showing up in the stack samples far more often for the relevant threads than the functions that handle the actual query data.  Remove all reflection to avoid the issue entirely.

This series also introduces eastwood and addresses all the issues it finds.  There are at least a few uncertain bits (i.e. that we may or may not want to keep for now, or in this series):

- The kitchensink jump to 3.1.3
- The addition of `eval-in-leningen` to the project file.  We could also just add it to the `:dev` profile, as far as eastwood is concernd, or we could add an eastwood suppression if we disagree with its assessment.
- The addition of `lein eastwood` and `lein check` "enforcement" in CI.  I currently lean in favor because eastwood found a number of issues here, and quite a few more in pdb when we added it.  I think I also currently lean in favor of `lein check` (which enforces "no reflection warnings") at least for libraries, because there's no telling where their calls will be used (e.g. could be in a tight loop).  Further, we can always opt sections of code out of reflection by bracketing regions with `(set! orig-warn-on-reflection false) ... (set! *warn-on-reflection* orig-warn-on-reflection)` or similar.

Also happy to break this up, if we'd prefer to add some of it in a later release.

2021-07-22 22:09 UTC, austb requested changes
This did not kick off any Travis tests, not sure if that's due to the branch rename, or if there's an issue with the Travis file.

We should make sure those are running and passing before merging this.

2021-07-22 22:13 UTC, austb commented on .travis.yml
>  branches:
Ah I found it in the Travis log.
```
Branch "main" not included per configuration. 
```
This branches config specifies only `master`

2021-07-22 23:28 UTC, austb approved these changes

2021-07-23 16:48 UTC, jonathannewman approved these changes

2021-07-23 16:48 UTC, merged